// Code generated by go-swagger; DO NOT EDIT.

package resource_class

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-runner-go-sdk/models"
)

// CreateResourceClassReader is a Reader for the CreateResourceClass structure.
type CreateResourceClassReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateResourceClassReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateResourceClassCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateResourceClassBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateResourceClassNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateResourceClassCreated creates a CreateResourceClassCreated with default headers values
func NewCreateResourceClassCreated() *CreateResourceClassCreated {
	return &CreateResourceClassCreated{}
}

/*
CreateResourceClassCreated describes a response with status code 201, with default header values.

A Runner resource-class object
*/
type CreateResourceClassCreated struct {
	Payload *models.ResourceClassInfo
}

// IsSuccess returns true when this create resource class created response has a 2xx status code
func (o *CreateResourceClassCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create resource class created response has a 3xx status code
func (o *CreateResourceClassCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create resource class created response has a 4xx status code
func (o *CreateResourceClassCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create resource class created response has a 5xx status code
func (o *CreateResourceClassCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create resource class created response a status code equal to that given
func (o *CreateResourceClassCreated) IsCode(code int) bool {
	return code == 201
}

func (o *CreateResourceClassCreated) Error() string {
	return fmt.Sprintf("[POST /v2/runner/resource][%d] createResourceClassCreated  %+v", 201, o.Payload)
}

func (o *CreateResourceClassCreated) String() string {
	return fmt.Sprintf("[POST /v2/runner/resource][%d] createResourceClassCreated  %+v", 201, o.Payload)
}

func (o *CreateResourceClassCreated) GetPayload() *models.ResourceClassInfo {
	return o.Payload
}

func (o *CreateResourceClassCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceClassInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateResourceClassBadRequest creates a CreateResourceClassBadRequest with default headers values
func NewCreateResourceClassBadRequest() *CreateResourceClassBadRequest {
	return &CreateResourceClassBadRequest{}
}

/*
CreateResourceClassBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type CreateResourceClassBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this create resource class bad request response has a 2xx status code
func (o *CreateResourceClassBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create resource class bad request response has a 3xx status code
func (o *CreateResourceClassBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create resource class bad request response has a 4xx status code
func (o *CreateResourceClassBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create resource class bad request response has a 5xx status code
func (o *CreateResourceClassBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create resource class bad request response a status code equal to that given
func (o *CreateResourceClassBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CreateResourceClassBadRequest) Error() string {
	return fmt.Sprintf("[POST /v2/runner/resource][%d] createResourceClassBadRequest  %+v", 400, o.Payload)
}

func (o *CreateResourceClassBadRequest) String() string {
	return fmt.Sprintf("[POST /v2/runner/resource][%d] createResourceClassBadRequest  %+v", 400, o.Payload)
}

func (o *CreateResourceClassBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *CreateResourceClassBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateResourceClassNotFound creates a CreateResourceClassNotFound with default headers values
func NewCreateResourceClassNotFound() *CreateResourceClassNotFound {
	return &CreateResourceClassNotFound{}
}

/*
CreateResourceClassNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateResourceClassNotFound struct {
	Payload *models.Errored
}

// IsSuccess returns true when this create resource class not found response has a 2xx status code
func (o *CreateResourceClassNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create resource class not found response has a 3xx status code
func (o *CreateResourceClassNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create resource class not found response has a 4xx status code
func (o *CreateResourceClassNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create resource class not found response has a 5xx status code
func (o *CreateResourceClassNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create resource class not found response a status code equal to that given
func (o *CreateResourceClassNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CreateResourceClassNotFound) Error() string {
	return fmt.Sprintf("[POST /v2/runner/resource][%d] createResourceClassNotFound  %+v", 404, o.Payload)
}

func (o *CreateResourceClassNotFound) String() string {
	return fmt.Sprintf("[POST /v2/runner/resource][%d] createResourceClassNotFound  %+v", 404, o.Payload)
}

func (o *CreateResourceClassNotFound) GetPayload() *models.Errored {
	return o.Payload
}

func (o *CreateResourceClassNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
