// Code generated by go-swagger; DO NOT EDIT.

package resource_class

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-runner-go-sdk/models"
)

// NewCreateResourceClassParams creates a new CreateResourceClassParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateResourceClassParams() *CreateResourceClassParams {
	return &CreateResourceClassParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateResourceClassParamsWithTimeout creates a new CreateResourceClassParams object
// with the ability to set a timeout on a request.
func NewCreateResourceClassParamsWithTimeout(timeout time.Duration) *CreateResourceClassParams {
	return &CreateResourceClassParams{
		timeout: timeout,
	}
}

// NewCreateResourceClassParamsWithContext creates a new CreateResourceClassParams object
// with the ability to set a context for a request.
func NewCreateResourceClassParamsWithContext(ctx context.Context) *CreateResourceClassParams {
	return &CreateResourceClassParams{
		Context: ctx,
	}
}

// NewCreateResourceClassParamsWithHTTPClient creates a new CreateResourceClassParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateResourceClassParamsWithHTTPClient(client *http.Client) *CreateResourceClassParams {
	return &CreateResourceClassParams{
		HTTPClient: client,
	}
}

/*
CreateResourceClassParams contains all the parameters to send to the API endpoint

	for the create resource class operation.

	Typically these are written to a http.Request.
*/
type CreateResourceClassParams struct {

	/* Body.

	   Runner resource-class information (payload)
	*/
	Body *models.ResourceClassPayload

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create resource class params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateResourceClassParams) WithDefaults() *CreateResourceClassParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create resource class params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateResourceClassParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create resource class params
func (o *CreateResourceClassParams) WithTimeout(timeout time.Duration) *CreateResourceClassParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create resource class params
func (o *CreateResourceClassParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create resource class params
func (o *CreateResourceClassParams) WithContext(ctx context.Context) *CreateResourceClassParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create resource class params
func (o *CreateResourceClassParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create resource class params
func (o *CreateResourceClassParams) WithHTTPClient(client *http.Client) *CreateResourceClassParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create resource class params
func (o *CreateResourceClassParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create resource class params
func (o *CreateResourceClassParams) WithBody(body *models.ResourceClassPayload) *CreateResourceClassParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create resource class params
func (o *CreateResourceClassParams) SetBody(body *models.ResourceClassPayload) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateResourceClassParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
