// Code generated by go-swagger; DO NOT EDIT.

package resource_class

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-runner-go-sdk/models"
)

// DeleteResourceClassReader is a Reader for the DeleteResourceClass structure.
type DeleteResourceClassReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteResourceClassReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteResourceClassNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteResourceClassBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteResourceClassNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteResourceClassNoContent creates a DeleteResourceClassNoContent with default headers values
func NewDeleteResourceClassNoContent() *DeleteResourceClassNoContent {
	return &DeleteResourceClassNoContent{}
}

/*
DeleteResourceClassNoContent describes a response with status code 204, with default header values.

Runner resource-class was deleted successfully.
*/
type DeleteResourceClassNoContent struct {
}

// IsSuccess returns true when this delete resource class no content response has a 2xx status code
func (o *DeleteResourceClassNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete resource class no content response has a 3xx status code
func (o *DeleteResourceClassNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete resource class no content response has a 4xx status code
func (o *DeleteResourceClassNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete resource class no content response has a 5xx status code
func (o *DeleteResourceClassNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete resource class no content response a status code equal to that given
func (o *DeleteResourceClassNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteResourceClassNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v2/runner/resource/{id}][%d] deleteResourceClassNoContent ", 204)
}

func (o *DeleteResourceClassNoContent) String() string {
	return fmt.Sprintf("[DELETE /v2/runner/resource/{id}][%d] deleteResourceClassNoContent ", 204)
}

func (o *DeleteResourceClassNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteResourceClassBadRequest creates a DeleteResourceClassBadRequest with default headers values
func NewDeleteResourceClassBadRequest() *DeleteResourceClassBadRequest {
	return &DeleteResourceClassBadRequest{}
}

/*
DeleteResourceClassBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type DeleteResourceClassBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this delete resource class bad request response has a 2xx status code
func (o *DeleteResourceClassBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete resource class bad request response has a 3xx status code
func (o *DeleteResourceClassBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete resource class bad request response has a 4xx status code
func (o *DeleteResourceClassBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete resource class bad request response has a 5xx status code
func (o *DeleteResourceClassBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete resource class bad request response a status code equal to that given
func (o *DeleteResourceClassBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *DeleteResourceClassBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v2/runner/resource/{id}][%d] deleteResourceClassBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteResourceClassBadRequest) String() string {
	return fmt.Sprintf("[DELETE /v2/runner/resource/{id}][%d] deleteResourceClassBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteResourceClassBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *DeleteResourceClassBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteResourceClassNotFound creates a DeleteResourceClassNotFound with default headers values
func NewDeleteResourceClassNotFound() *DeleteResourceClassNotFound {
	return &DeleteResourceClassNotFound{}
}

/*
DeleteResourceClassNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteResourceClassNotFound struct {
	Payload *models.Errored
}

// IsSuccess returns true when this delete resource class not found response has a 2xx status code
func (o *DeleteResourceClassNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete resource class not found response has a 3xx status code
func (o *DeleteResourceClassNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete resource class not found response has a 4xx status code
func (o *DeleteResourceClassNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete resource class not found response has a 5xx status code
func (o *DeleteResourceClassNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete resource class not found response a status code equal to that given
func (o *DeleteResourceClassNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteResourceClassNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v2/runner/resource/{id}][%d] deleteResourceClassNotFound  %+v", 404, o.Payload)
}

func (o *DeleteResourceClassNotFound) String() string {
	return fmt.Sprintf("[DELETE /v2/runner/resource/{id}][%d] deleteResourceClassNotFound  %+v", 404, o.Payload)
}

func (o *DeleteResourceClassNotFound) GetPayload() *models.Errored {
	return o.Payload
}

func (o *DeleteResourceClassNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
