// Code generated by go-swagger; DO NOT EDIT.

package resource_class

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-runner-go-sdk/models"
)

// ListResourceClassesReader is a Reader for the ListResourceClasses structure.
type ListResourceClassesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListResourceClassesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListResourceClassesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListResourceClassesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListResourceClassesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListResourceClassesOK creates a ListResourceClassesOK with default headers values
func NewListResourceClassesOK() *ListResourceClassesOK {
	return &ListResourceClassesOK{}
}

/*
ListResourceClassesOK describes a response with status code 200, with default header values.

A sequence of Runner resource-classes
*/
type ListResourceClassesOK struct {
	Payload *models.ResourceClassesInfo
}

// IsSuccess returns true when this list resource classes o k response has a 2xx status code
func (o *ListResourceClassesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list resource classes o k response has a 3xx status code
func (o *ListResourceClassesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list resource classes o k response has a 4xx status code
func (o *ListResourceClassesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list resource classes o k response has a 5xx status code
func (o *ListResourceClassesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list resource classes o k response a status code equal to that given
func (o *ListResourceClassesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListResourceClassesOK) Error() string {
	return fmt.Sprintf("[GET /v2/runner/resource][%d] listResourceClassesOK  %+v", 200, o.Payload)
}

func (o *ListResourceClassesOK) String() string {
	return fmt.Sprintf("[GET /v2/runner/resource][%d] listResourceClassesOK  %+v", 200, o.Payload)
}

func (o *ListResourceClassesOK) GetPayload() *models.ResourceClassesInfo {
	return o.Payload
}

func (o *ListResourceClassesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceClassesInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListResourceClassesBadRequest creates a ListResourceClassesBadRequest with default headers values
func NewListResourceClassesBadRequest() *ListResourceClassesBadRequest {
	return &ListResourceClassesBadRequest{}
}

/*
ListResourceClassesBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type ListResourceClassesBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this list resource classes bad request response has a 2xx status code
func (o *ListResourceClassesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list resource classes bad request response has a 3xx status code
func (o *ListResourceClassesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list resource classes bad request response has a 4xx status code
func (o *ListResourceClassesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list resource classes bad request response has a 5xx status code
func (o *ListResourceClassesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list resource classes bad request response a status code equal to that given
func (o *ListResourceClassesBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListResourceClassesBadRequest) Error() string {
	return fmt.Sprintf("[GET /v2/runner/resource][%d] listResourceClassesBadRequest  %+v", 400, o.Payload)
}

func (o *ListResourceClassesBadRequest) String() string {
	return fmt.Sprintf("[GET /v2/runner/resource][%d] listResourceClassesBadRequest  %+v", 400, o.Payload)
}

func (o *ListResourceClassesBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *ListResourceClassesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListResourceClassesNotFound creates a ListResourceClassesNotFound with default headers values
func NewListResourceClassesNotFound() *ListResourceClassesNotFound {
	return &ListResourceClassesNotFound{}
}

/*
ListResourceClassesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListResourceClassesNotFound struct {
	Payload *models.Errored
}

// IsSuccess returns true when this list resource classes not found response has a 2xx status code
func (o *ListResourceClassesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list resource classes not found response has a 3xx status code
func (o *ListResourceClassesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list resource classes not found response has a 4xx status code
func (o *ListResourceClassesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list resource classes not found response has a 5xx status code
func (o *ListResourceClassesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list resource classes not found response a status code equal to that given
func (o *ListResourceClassesNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ListResourceClassesNotFound) Error() string {
	return fmt.Sprintf("[GET /v2/runner/resource][%d] listResourceClassesNotFound  %+v", 404, o.Payload)
}

func (o *ListResourceClassesNotFound) String() string {
	return fmt.Sprintf("[GET /v2/runner/resource][%d] listResourceClassesNotFound  %+v", 404, o.Payload)
}

func (o *ListResourceClassesNotFound) GetPayload() *models.Errored {
	return o.Payload
}

func (o *ListResourceClassesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
