// Code generated by go-swagger; DO NOT EDIT.

package resource_class

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListResourceClassesParams creates a new ListResourceClassesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListResourceClassesParams() *ListResourceClassesParams {
	return &ListResourceClassesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListResourceClassesParamsWithTimeout creates a new ListResourceClassesParams object
// with the ability to set a timeout on a request.
func NewListResourceClassesParamsWithTimeout(timeout time.Duration) *ListResourceClassesParams {
	return &ListResourceClassesParams{
		timeout: timeout,
	}
}

// NewListResourceClassesParamsWithContext creates a new ListResourceClassesParams object
// with the ability to set a context for a request.
func NewListResourceClassesParamsWithContext(ctx context.Context) *ListResourceClassesParams {
	return &ListResourceClassesParams{
		Context: ctx,
	}
}

// NewListResourceClassesParamsWithHTTPClient creates a new ListResourceClassesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListResourceClassesParamsWithHTTPClient(client *http.Client) *ListResourceClassesParams {
	return &ListResourceClassesParams{
		HTTPClient: client,
	}
}

/*
ListResourceClassesParams contains all the parameters to send to the API endpoint

	for the list resource classes operation.

	Typically these are written to a http.Request.
*/
type ListResourceClassesParams struct {

	/* Namespace.

	   Namespace to filter by.
	*/
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list resource classes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListResourceClassesParams) WithDefaults() *ListResourceClassesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list resource classes params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListResourceClassesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list resource classes params
func (o *ListResourceClassesParams) WithTimeout(timeout time.Duration) *ListResourceClassesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list resource classes params
func (o *ListResourceClassesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list resource classes params
func (o *ListResourceClassesParams) WithContext(ctx context.Context) *ListResourceClassesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list resource classes params
func (o *ListResourceClassesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list resource classes params
func (o *ListResourceClassesParams) WithHTTPClient(client *http.Client) *ListResourceClassesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list resource classes params
func (o *ListResourceClassesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the list resource classes params
func (o *ListResourceClassesParams) WithNamespace(namespace string) *ListResourceClassesParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the list resource classes params
func (o *ListResourceClassesParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *ListResourceClassesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param namespace
	qrNamespace := o.Namespace
	qNamespace := qrNamespace
	if qNamespace != "" {

		if err := r.SetQueryParam("namespace", qNamespace); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
