// Code generated by go-swagger; DO NOT EDIT.

package resource_class

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new resource class API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for resource class API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateResourceClass(params *CreateResourceClassParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateResourceClassCreated, error)

	DeleteResourceClass(params *DeleteResourceClassParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteResourceClassNoContent, error)

	ListResourceClasses(params *ListResourceClassesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListResourceClassesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateResourceClass creates a runner resource class

Create a Runner resource-class.
*/
func (a *Client) CreateResourceClass(params *CreateResourceClassParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*CreateResourceClassCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateResourceClassParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "CreateResourceClass",
		Method:             "POST",
		PathPattern:        "/v2/runner/resource",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateResourceClassReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateResourceClassCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for CreateResourceClass: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteResourceClass deletes a runner resource class

Delete a Runner resource-class. Ensure associated tokens are deleted first.
*/
func (a *Client) DeleteResourceClass(params *DeleteResourceClassParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteResourceClassNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteResourceClassParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteResourceClass",
		Method:             "DELETE",
		PathPattern:        "/v2/runner/resource/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteResourceClassReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteResourceClassNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteResourceClass: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListResourceClasses lists runner resource classes by namespace

List Runner resource classes by namespace.
*/
func (a *Client) ListResourceClasses(params *ListResourceClassesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*ListResourceClassesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListResourceClassesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "ListResourceClasses",
		Method:             "GET",
		PathPattern:        "/v2/runner/resource",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListResourceClassesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListResourceClassesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for ListResourceClasses: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
